satis:
    image: prasantk/docker-satis:4.2
    hostname: satis
    volumes:
        - "/var/tmp/composer:/root/.composer"
        - "~/.ssh/id_rsa:/var/tmp/id"
    environment:
        PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
        CRONTAB_FREQUENCY: "*/1 * * * *"
        VIRTUAL_HOST: satis.localhost
    ports:
        - 3333:3000
